spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: ${DB_USER} # = root
    password: ${DB_PASSWORD} # = "your password"
  jpa:
    show-sql: true